### ISSUE TITLE
Increase the Verification time at DNSMASQ

### ISSUE THREAD

**Issue by arbazkiraak** [integrity-sa/burpcollaborator-docker#4]
Hello,

Thanks for writing this script, Do increase the `10 seconds` to user specified time. so that user can go manually & add the TXT records from dns settings.

```
Launching DNSMASQ...
DNSMASQ CMD: 
Waiting 10 seconds for DNS changes to propagate
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. 
```

**Comment by morisson** [comment]
@arbazkiraak , I'm not sure how you're trying it, but you do not need to manually do anything. The dnsmasq server will be auto configured.

You need to make sure you have correctly delegated the subdomain to the IP address where you're running these collaborator scripts.
