### ISSUE TITLE
Waiting 10 seconds for DNS changes to propagate?

### ISSUE THREAD

**Issue by Phoenix1112** [integrity-sa/burpcollaborator-docker#7]
hello. Thank you for the wonderful project... it waits for 10 seconds while creating the certificate and ends the process before i complete txt registration.what should I do?  
-------------------------------------------------------------------------------------------------------------------------------------------
edit:

I think the certificate can be created for cloudflare alone. I was trying to make DNS settings with google cloud before.therefore, it was waiting for 10 seconds while creating the certificate. now I started using cloudflare to make dns settings.. but again I am facing a problem. you would suggest dns configuration on the home page as follows.

example: domain name( burp.collaborator.com)

A ------------burp.collaborator.com ------------54.54.55.44

NS ----------burp.collaborator.com ----------- burp.collaborator.com

cloudflare does not allow me to configure dns as above... 

orginal error:
NS records already exist with that host. (Code: 81056)

but if I set up dns as follows,  cloudflare allow it

example:

A ------------ns1.burp.collaborator.com --------------54.54.55.44
NS ----------burp.collaborator.com -------------------ns1.burp.collaborator.tk

do you think this could be a problem?

**Comment by Phoenix1112** [comment]
i can not add txt record.. because it turns itself off in 10 seconds... Why is this happening...

**Comment by morisson** [comment]
Please check issues #4 and #5.
