### ISSUE TITLE
Listen TCP 0.0.0.0:53 bind address already in use. 

### ISSUE THREAD

**Issue by Hax0rG1rl** [integrity-sa/burpcollaborator-docker#8]
Hi, 

I got this installed on a Vultr VPS. All good with the deployment until I got this: 

![image](https://user-images.githubusercontent.com/3704868/78648669-676f3380-7910-11ea-90e5-ebea2ccd5450.png)

![image](https://user-images.githubusercontent.com/3704868/78648681-6f2ed800-7910-11ea-8bad-d9b44251e29c.png)

Do you have any workaround for this one? 

Thank you!

**Comment by morisson** [comment]
You can't have any other dns server running on the same host, and you have systemd-resolved running, as shown in your screenshot.

**Comment by Hax0rG1rl** [comment]
Hi, 

I redeployed the server and I get this now. Any ideas why? 

![image](https://user-images.githubusercontent.com/3704868/91628241-ea08a480-ea11-11ea-8ed5-cdb23480e45a.png)

![image](https://user-images.githubusercontent.com/3704868/91628254-0e648100-ea12-11ea-8393-2d7b403c4955.png)

Thanks!

**Comment by morisson** [comment]
Probably the collaborator settings on burp...
